server:
  port: 7777
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  server:
    enableSelfPreservation: false 
  client:
    registerWithEureka: false
    fetchRegistry: false
    
